### ISSUE TITLE
How to obtain the messages in the "messages" queues in the server and client

### ISSUE THREAD

**Issue by welkerCode** [MouseEvent/javax.server#2]
Hey!  I managed to build your project and have written a main method in another class I made to test the connection:

package javax.server;

public class JavaxServerMain {
    public static void main(String[] args){
        String serverAddress = "";
        int port = 5454;
        int messageHandlingThreadCount = 0;

        // Initialize and start the Server
        Server server = new Server(port, messageHandlingThreadCount);
        server.start();

        // Initialize and start the Client
        Client client = new Client(serverAddress, port);
        client.start();

        // Prepare the messages
        String clientMsg = "Incoming from the client";
        String serverMsg = "Incoming from the server";
        String clientAuth = Integer.toString(client.getClientId());
        String serverAuth = "The Server...";
        QuadMsg toServer = new QuadMsg(clientMsg, clientAuth);
        QuadMsg toClient = new QuadMsg(serverMsg, serverAuth);

        while(true){
            // Have the client send a message to the server, and the server to the client.
            client.send(toServer);
            server.sendToAll(toClient);
        }

        // Now here, obtain the messages and print them.

        // When you are done, shut down the client and the server
        //client.shutDown();
        //server.shutDown();
    }
}

I managed to step through the program, and see that the client object is found within the server's clients map, however, it seems that the messages I have been sending between the server and client rarely make it to each other's "messages" queues.  While nothing ever arrives on the client's side, the server's side occasionally gets a message, which then disappears the very next step.

Do you know what I am missing, and what I can do to retrieve the messages from the queues?

**Comment by mordechaim** [comment]
Haven't touched this project for quite a while, I will need to get
myself back into it.

Will take a look and try to help when I have time.

**Comment by mordechaim** [comment]
Off the top of my head, did you call sync()? Otherwise the server
returns immediately and gets shut down with shutdown() without doing
anything.

**Comment by mordechaim** [comment]
Hard to judge from your snippet but looks like you get stuck in an infinite loop before hooking up message listeners. Move the listener code before the loop. 

The queued message will always get removed as soon the handler thread gets to it. It then looks for registered listeners and forwards it. If no listener is found, the message is just ignored and removed.

**Comment by welkerCode** [comment]
Thanks for the tips!  I didn't understand how the listeners work, and upon further investigation, I learned that in order to access the messages sent between the server and the client you need to use/write the methods within the ServerAdapter and ClientAdapter classes.  I took the client.send and server.send methods out of that while(true) loop, and added a client.sync() after sending the messages.  Now I am able to send and receive messages.  Thank you for your help mordechaim!

I have another question if you have time: what is an example of using the client.sync() or server.sync() methods?  I understand that they block the thread that called them, but when would you want to use them (I am still a little new to multi-threading in Java)?

Thank you again for your help!

**Comment by mordechaim** [comment]
I'm happy to hear you solved your problem.

For your second question, all threads in both the client and the
server are set as daemon threads, meaning when the main thread ends
and no other thread is running these threads gets shut down
automatically to prevent the JVM from hanging indefinitly.

To prevent the main to exit as long the server or client runs, you can
call the sync() method which waits until it shuts down (either by
calling shutDown() or by server disconnection or failure) or by
calling unsync().
