### ISSUE TITLE
Communicating with other languages

### ISSUE THREAD

**Issue by welkerCode** [MouseEvent/javax.server#3]
Mordechaim,

Thanks again for your help earlier!  I managed to modify your script so that JSON objects can be passed between clients instead of Serializable objects. My reason for doing this is so that I can send information from a Java client to a Python Client.  I am trying to better understand how the Acception class works in the server.java file.  

I try to have my Python client connect to the Server while the main function is waiting for a user input.  It appears that my Python client manages to connect to the socket, but it doesn't seem to trigger in the server.java's acception.run() or acception.authenticate() methods in the debugger, and after sending my message and checking the server's list of clients, it only lists the two Java clients that I initialize in the beginning, but not the Python one.

Clearly, the server is either rejecting or not noticing the Python client trying to connect to the designated socket.  However, the Python client always seems to receive some garbage characters from the server upon connecting to it.  

What does it take for a Java client to connect to the server?  I am hoping to mimic the behavior in Python so that I can trick the server into at least accepting the client and assigning it an id (not necessarily a Client object).  

My main file:

package javax.server;

import java.util.Scanner;
import java.util.concurrent.ArrayBlockingQueue;
import org.json.*;

public class JavaxServerMain {
    public static void main(String[] args){
        String serverAddress = "";
        int port = 50012;
        int messageHandlingThreadCount = 0;

        // toBRECCIAQ is for messages received from the server directed towards BRECCIA
        // toQUADQ is for messages received from the server directed towards the Quadcopter
        ArrayBlockingQueue toBRECCIAQ = new ArrayBlockingQueue(1024);
        ArrayBlockingQueue toQUADQ = new ArrayBlockingQueue(1024);

        // Initialize and start the Server
        Server server = new Server(port, messageHandlingThreadCount);
        server.start();

        // Initialize and start the Clients
        Client brecciaClient = new Client(serverAddress, port);
        Client quadClient = new Client(serverAddress, port);
        brecciaClient.start();
        quadClient.start();

        String response = "start text";

        while(!response.equals("exit"))
        {
            // Ask for user input
            Scanner input = new Scanner(System.in);
            response = input.nextLine();

            JSONObject obj = new JSONObject();

            try {
                obj.put("message", response);
                obj.put("sender", brecciaClient.getClientId());
                obj.put("receiver", quadClient.getClientId());
            } catch (JSONException e) {
                e.printStackTrace();
            }

            // Have the client send a message to the server, and the server to the client.
            boolean brecciaMsgSent = brecciaClient.send(obj);
            System.out.println(brecciaMsgSent);
            //boolean quadMsgSent = quadClient.send(toBRECCIA);
        }

        /*
        String userInput = "Beginning";
        String termInput = "exit";
        while(!userInput.equals(termInput)) {

        }*/

        // Now here, obtain the messages and print them.
        try {
            brecciaClient.sync();
            quadClient.sync();
        } catch (InterruptedException e) {
            System.out.println("Sync didn't work...");
            e.printStackTrace();
        }

        // When you are done, shut down the client and the server
        brecciaClient.shutDown();
        quadClient.shutDown();
        server.shutDown();
    }
}

I overloaded the send functions in the client, server and connectionToClient classes so that they can accept Serializable or JSONObjects.  Other than that, the code is the other files is the same.

Any tips?

Thank you for your help!

**Comment by mordechaim** [comment]
The issue you're experiencing is a Command.HANDSHAKE object that's
being sent to make sure it only accepts my client implementation.

You'll either have to remove this operation completely, or do the
authentication in json instead of a Command object.

In any event, if you want to build a real-world server, use JavaEE and
JaxRS instead. This is really for embedding the server in a desktop
application, like for multi-player gaming.

**Comment by welkerCode** [comment]
Thanks for your tip!  I managed to get the program to communicate with the Python client after removing the Handshake protocols and implementing a new version of Send using JSON.  The program functions exactly the way I need it to.  Thank you for helping me!
